# Generated by Django 4.1.7 on 2023-02-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Create Report',
                'permissions': [('can_create_report', 'Can create report')],
                'default_permissions': [],
            },
        ),
    ]
