# Generated by Django 4.1.7 on 2023-02-25 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_attendance_students'),
        ('actions', '0002_createreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuarterlyWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.student')),
            ],
            options={
                'verbose_name_plural': 'Pick Quarterly Winners',
                'permissions': [('can_view_winners', 'Can view quarterly winners'), ('can_pick_winners', 'Can pick quarterly winners')],
                'default_permissions': [],
            },
        ),
    ]
