# Generated by Django 4.1.7 on 2023-02-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_quarterlywinner'),
    ]

    operations = [
        migrations.AddField(
            model_name='quarterlywinner',
            name='points',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
