# Generated by Django 4.1.7 on 2023-02-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_quarterlywinner_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'Import/Backup Data',
                'permissions': [('can_import_data', 'Can import data'), ('can_backup_data', 'Can backup data')],
                'default_permissions': [],
            },
        ),
    ]
