# Generated by Django 4.1.7 on 2023-02-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_student_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='students',
            field=models.ManyToManyField(blank=True, to='main.student'),
        ),
    ]
